### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by k----n**

### CODE REVIEW

**Comment by vchrombie** [comment]
Nice catch, thanks for your contribution. Do you mind fixing the sign-off issue?
Please let me know if you need help.

**Comment by k----n** [comment]
@vchrombie It should be fixed. Let me know if anything else needs to change.

**Comment by vchrombie** [comment]
Thanks for adding some more changes, @k----n.

The PR looks great! Would you mind squashing the commits into one so that I proceed for merging it.

Thank you for your contribution.

**Comment by k----n** [comment]
@vchrombie It should be squashed.

**Review by vchrombie — APPROVED** [review]
LGTM!
Thanks for opening the PR @k----n.

**Pull request merged**
