### PR TITLE
fixed username and pass for kibiter login

### PR DESCRIPTION
**Pull request by imnitishng**
Fixed username and password for kibiter login in troubleshooting section causing permission issue in elasticsearch while creating indexes
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>

### CODE REVIEW

**Comment by valeriocos** [comment]
ping @imnitishng :)

**Comment by valeriocos** [comment]
supposing that the chaoss/grimoirelab-sirmordred is your upstream and
your fork is origin. Can you do the following in the branch `readme_fix`?
```
git fetch upstream
git rebase upstream/master
git rebase -i HEAD~2
in the new editor squash the two commits by changing `pick` with `f` for the last commit
git log --oneline to check that you have just one new commit (wrt to the upstream master branch)
git push origin -f
```

**Comment by imnitishng** [comment]
Okay I will thanks this is my first time dealing with conflicts, sorry for the delay.

**Comment by valeriocos** [comment]
no worries , thanks @imnitishng

**Comment by imnitishng** [comment]
Don't know what I just did I hope this is right.

**Comment by valeriocos** [comment]
@imnitishng thank you for reworking the PR. You forgot to resolve the conflicts at https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1334. Please find some explanations below.

A conflict has the following shape:
- the content of the HEAD branch appears between <<<< HEAD and ====
- what is between === and >>>> shows the conflicting content
- example:
```
<<<<<<< HEAD
 #### Empty Index
=======
  The credentials used for login should be username: `admin` and password: `admin`.
>>>>>>> fixed username and pass for kibiter login
```

To resolve the conflict you have to manually fix it. For instance, a possible resolution of the example above could be to move the conflicting content before  `#### Empty Index`
```
The credentials used for login should be username: `admin` and password: `admin`.

 #### Empty Index
``` 

Once done, you have to add the new changes (`git add <file>`) and then execute `git rebase --continue` (in case you are rebasing).

> https://github.com/chaoss/grimoirelab-sirmordred/pull/420#issuecomment-598563397

Take your time :) Consider this PR as a way to learn the Git conflict resolution, don't hesitate to ask questions

**Comment by imnitishng** [comment]
I hope things are right this time, if not please inform, I'll be happy to learn and fix. Thank you @valeriocos for being so supportive.

**Comment by valeriocos** [comment]
Almost :)
These parts shouldn't be there:
- https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1291
- https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1418

Only this change should be:
- https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1334

**Comment by imnitishng** [comment]
I added those parts intentionally because I felt it was required for secured kibiter docker file. Should I still remove them?

Also [this line](https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1291) was not added by me, I only changed 
https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1334
and
https://github.com/chaoss/grimoirelab-sirmordred/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1418

**Comment by valeriocos** [comment]
ok I see :) Let's merge it, thanks @imnitishng !

**Pull request merged**
