### PR TITLE
Handle creating alias of alias, use original alias target then, fixes #241

### LINKED ISSUE #241: Cannot create alias of alias - Mordred fails.
When I configured my ElasticSearch instance to use aliases it causes Mordred to fail.

My `/git` is an alias that points to `git_v1` same with all other data sources.
So everyone like `jira_raw` is really an alias to `jira_raw_v1`.
This is because I want to be able to easily change what `git`, `jira`, `github` and others mean.
It was Ok for Perceval and OK for ELK but Mordred tries to create `alias of alias` and fails, the exact error message is:
```
2018-10-18 13:06:49,670 - sirmordred.task_manager - ERROR - Exception in Task Manager 400 Client Error: Bad Request for url: http://localhost:9200/_aliases
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_manager.py", line 92, in run
    task.execute()
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_enrich.py", line 308, in execute
    raise e
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_enrich.py", line 298, in execute
    self.__enrich_items()
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_enrich.py", line 181, in __enrich_items
    task_aliases.execute()
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_panels.py", line 534, in execute
    self.__create_aliases()
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_panels.py", line 520, in __create_aliases
    self.__create_alias(es_col_url, index_raw, real_alias + "-raw")
  File "/usr/local/lib/python3.6/dist-packages/sirmordred/task_panels.py", line 495, in __create_alias
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:9200/_aliases
```

I'll try to dig Python code to fix that and then eventually create a PR.

### PR DESCRIPTION
**Pull request by lukaszgryglicki**
This fixes #241 
Signed-off-by: Lukasz Gryglicki <lukaszgryglicki@o2.pl>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Should I add some tests? If so please let me know where, possibly point me to some examples, I'm totally new to this project and have almost no time...

**Comment by lukaszgryglicki** [comment]
ping.

**Comment by valeriocos** [comment]
pong :) sorry for the late reply @lukaszgryglicki 

Overall the PR looks OK, if this code helps you in your work it can be accepted with some minor changes (replace `logger.debug` with `logger.warning`). However note that this change will have an impact on the visualization component (kibiter). 

Kibiter uses the aliases (set [here](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_panels.py#L376)) to connect with/visualize the data. [Aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) allow to work on more indexes at the same time and associate filters. Furthermore, we use them to perform transparent rename operations (pointing the alias from an index to another one), which ElasticSearch doesn't support with a unique command.

WRT the tests, you can have a look at [test_task_panels](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/tests/test_task_panels.py). 

When testing your PR, I got an 400 HTTP error when inserting an alias already used as index name. You should modify [this except block](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_panels.py#L506) to handle error.

**Comment by lukaszgryglicki** [comment]
Thanks, will address when i have some time.

**Comment by lukaszgryglicki** [comment]
On it now. It doesn't have an impact on the Kibiter because it only checks if "source" index (the one to create an alias to it) isn't already an alias. If it is an alias, then creating alias to where the original index points to. I'll add coverage.

**Comment by lukaszgryglicki** [comment]
Not sure what do you mean by modifying except block. "when inserting an alias already used as index name", my code is not changing this, my code only tries to detect if source index is already an alias, so described error should happen even without this PR, right?

**Comment by lukaszgryglicki** [comment]
Also not sure how to add tests for it. I don't see any alias releted tests :/. How can I run the tests, that is my first question, I don't see any info in README.md.

**Comment by valeriocos** [comment]
To execute the tests you can run [run_tests.py](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/tests/run_tests.py), it will execute all tests of mordred.

You can add a class like the one below in [test_task_panels](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/tests/test_task_panels.py), and define methods to test your code (if possible).
```
class TestTaskPanelsAliases(unittest.TestCase):
    """TaskPanelsAliases tests"""

    def test_initialization(self):
        """Test whether attributes are initializated"""

        config = Config(CONF_FILE)
        task = TaskPanelsAliases(config)

        self.assertEqual(task.config, config)
   ...
```

Travis fails due to a `flake8` error, the list of error messages you see don't affect the outcome of the Travis execution.

Hope this helps.

**Comment by valeriocos** [comment]
The flake8 errors were due to a new version of the same package. As soon as the PR https://github.com/chaoss/grimoirelab-sirmordred/pull/247 is merged, the errors will be gone.

**Comment by valeriocos** [comment]
@lukaszgryglicki any news about this PR? how is it going?

**Comment by valeriocos** [comment]
@lukaszgryglicki I'm closing this PR, which seems inactive and has conflicts with the current code base. Feel free to reopen if you want to rework it

**Pull request closed without merging**
