### PR TITLE
[doc] Add sample cocom fields

### PR DESCRIPTION
**Pull request by snack0verflow**
This commit adds the sample `projects.json` and `setup.cfg` for cocom.

### CODE REVIEW

**Comment by snack0verflow** [comment]
@valeriocos Could you please have a look at this change? Thanks :)

**Comment by valeriocos** [comment]
Please @snack0verflow consider to submit a similar PR for code license data (colic backend of graal). Thanks :)

**Comment by snack0verflow** [comment]
@valeriocos sure, also please let me know when can I text you on IRC

**Comment by valeriocos** [comment]
great! I'm going to be on IRC until 16h (Madrid time)

**Comment by snack0verflow** [comment]
@valeriocos pinged you on IRC

**Pull request merged**
