### PR TITLE
Add Mattermost study.md

### PR DESCRIPTION
**Pull request by Virkeipa**
Update Mattermost: add demography study

### CODE REVIEW

**Comment by jjmerchante** [comment]
Congratulations on your first Pull Request, one comment to write good commit messages, and one required action.

[Read this document for writing good commit messages.](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages)

The commit title summarizes the changes in a few words. In this case, `Update README.md` doesn't provide details about what is updated. `Update README.md including Mattermost studies` or `Add Mattermost study to README` shows more information about the change.

[CHAOSS requires that contributions are signed-off](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions), you need to add a new line in the commit with the following format:
```
Signed-off-by: Your Name <YourName@example.org>
```

Thank you!

**Comment by jjmerchante** [comment]
LGTM

**Comment by vchrombie** [comment]
Thanks for the PR @Virkeipa, I rebased the PR to include the latest changes.
@sduenas @jjmerchante can you please review this and merge it when you have time.

**Review by zhquan — APPROVED** [review]
LGTM thanks

**Pull request closed without merging**
