### PR TITLE
resolving issue #192

### PR DESCRIPTION
**Pull request by kaushik-p9**
The necessary changes have been made as mentioned in issue #192

### CODE REVIEW

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9. LGTM

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9 , LGTM.

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9 , LGTM.

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9 , LGTM.

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9 , LGTM.

**Comment by valeriocos** [comment]
Thank you for this PR @kaushik-p9

**Comment by kaushik-p9** [comment]
Hello sir, just wanted to know if CHAOSS will be participating as an
organization for gsoc 2019?

**Comment by jgbarah** [comment]
Very likely.

**Pull request merged**
