### PR TITLE
[graal] Add configuration for Graal integration in ELK

### PR DESCRIPTION
**Pull request by inishchith**
- Added the configuration required to trigger enricher and study integration of Graal from ELK. 

> **Note:** The tests would fail until we merge https://github.com/chaoss/grimoirelab-elk/pull/672

/cc @valeriocos 

Signed-off-by: inishchith <inishchith@gmail.com>

### CODE REVIEW

**Comment by inishchith** [comment]
@valeriocos Sure. I'm just finishing up with the scancode-cli task. This along with sigils#PR should be updated in next hour. 
Sorry for the delay

**Comment by valeriocos** [comment]
no worries, thanks for quick reply

**Comment by inishchith** [comment]
@valeriocos Thanks for all the help.
I've included the code references from https://github.com/chaoss/grimoirelab-elk/pull/672 after testing them on entire toolchain

**Comment by valeriocos** [comment]
you're welcome :)

**Comment by valeriocos** [comment]
@sduenas feel free to have a look at it

**Pull request merged**
