### PR TITLE
[micro-mordred] Improve error messages in micro.py

### PR DESCRIPTION
**Pull request by rohanreddych**
Improve error message when config file is not provided while executing micro.py.

Signed-off-by: Rohan Reddy <rohan.ch.reddy@gmail.com>

### CODE REVIEW

**Comment by rohanreddych** [comment]
Before 
```
micro.py --raw --enrich --backends git
Traceback (most recent call last):
  File "/home/rohan/2work/sources/grimoirelab-sirmordred/utils/micro.py", line 230, in <module>
    micro_mordred(args.cfg_path, args.backend_sections,
  File "/home/rohan/2work/sources/grimoirelab-sirmordred/utils/micro.py", line 55, in micro_mordred
    config = Config(cfg_path)
  File "/home/rohan/2work/sources/grimoirelab-sirmordred/sirmordred/config.py", line 63, in __init__
    self.__read_conf_files()
  File "/home/rohan/2work/sources/grimoirelab-sirmordred/sirmordred/config.py", line 670, in __read_conf_files
    parser.read(conf_file)
  File "/usr/lib/python3.8/configparser.py", line 694, in read
    for filename in filenames:
TypeError: 'NoneType' object is not iterable
```
After

```
micro.py --raw --enrich --backends git
Config file path not provided
```

**Comment by vchrombie** [comment]
Hi @rohanreddych, thanks for submitting the PR.
Can you please fix the flake8 errors, you can check the build log for the error?

Please let me know if you need any help.

**Comment by vchrombie** [comment]
Also, it would be great if you can update the commit message as per the [commit guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages).

You can wrap the body at 72 characters. If it is too long, you can break it in two lines.

You can amend the commit and force push the branch. 
Thanks.

**Comment by rohanreddych** [comment]
@vchrombie I Changed the commit message.

**Comment by sduenas** [comment]
Merged. Thanks for your contribution.

**Pull request closed without merging**
